Catumblr/Controllers/CommentController.cs
using Catumblr.BLL.DTO;
using Catumblr.BLL.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace Catumblr.Controllers
{
    public class CommentController : BaseController
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        public ActionResult Add(int postId)
        {
            return View("_Add");
        }

        [HttpPost]
        public ActionResult Add(CommentDto commentDto)
        {           
            _commentService.Add(commentDto, UserName, UserId);
            return RedirectToAction("GetPost", "Post", new {id = commentDto.PostId});
        }
    }
}

Catumblr/Views/Comment/_Add.cshtml
@model Catumblr.BLL.DTO.CommentDto

@if (User.Identity.IsAuthenticated)
{
    <form asp-action="Add" asp-controller="Comment" asp-route-postId="@ViewBag.PostId">
        <div class="form-group">
            <input id="Text" asp-for="Text" type="text" class="form-control"/>
            <input id="PostId" type="hidden" asp-for="PostId" value="@ViewBag.PostId"/>
        </div>
        <button class="btn col-md-offset-11" type="submit" id="addCommentButton">Comment</button>
    </form>
}

<script src="~/js/comment.js"></script>
<script src="~/js/dateformat.js"></script>

Catumblr/Views/Comment/_RenderComments.cshtml
@using Catumblr.BLL.DTO
@model IEnumerable<Catumblr.DAL.Models.Comment>

<div class="container-fluid">
    <div>
        <h3><small id="commentCount" class="pull-right">@Model.Count() comments</small> Comments </h3>
    </div> 
    <div class="comments-list" id="commentList">
        @{ await Html.RenderPartialAsync("~/Views/Comment/_Add.cshtml", new CommentDto());}
        <div id="firstComment"></div>
        @foreach (var comment in Model)
        {
            <div class="media">
                <h5><small class="pull-right">@comment.Time</small></h5>
                <div class="media-body">
                    <h5 class="media-heading user_name">@comment.UserName</h5>
                    @comment.Text
                </div>
            </div>
        }
    </div>
</div>