Catumblr/Controllers/BlogController.cs
using Catumblr.BLL.DTO;
using Catumblr.BLL.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace Catumblr.Controllers
{
    public class BlogController : BaseController
    {
        private readonly IBlogService _blogService;

        public BlogController(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public IActionResult Index()
        {
            var blogs = _blogService.GetUserBlogs(UserId);
            return View(blogs);
        }

        [HttpPost]
        public ActionResult Create(BlogDto blogDto)
        {
            _blogService.Add(blogDto, UserId);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int blogId)
        {
            _blogService.Delete(blogId);
            return RedirectToAction("Index");
        }
    }
}

Catumblr/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Mvc.Razor.Extensions

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Catumblr</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" link href="~/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" />

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/signalr/signalr.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" asp-route-takeCount="3" class="navbar-brand">Catumblr</a>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="Blog" asp-action="Index" class="navbar-brand">@Localizer["Blogs"]</a>
                    @(await Component.InvokeAsync("Statistic", new { postCount = 5 }))
                    <a asp-area="" asp-controller="Post" asp-action="Create" class="navbar-brand">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                }                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">@Localizer["About"]</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content" id="body-content">
        @RenderBody()
        <footer>
            <hr />
            <p>&copy; 2018 - Catumblr</p>
        </footer>
    </div>

    <environment include="Development">
        
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Catumblr/Views/Shared/_Likes.cshtml
@model Catumblr.Models.ViewModels.PostViewModel
<div class="col-md-1 container-flex">
    <h4 id="likeCount">@Model.GetLikesCount</h4>
    <a id="likeButton" class="btn glyphicon glyphicon-heart"></a>
</div>

@Html.HiddenFor(viewModel => viewModel.PostId)
@Html.HiddenFor(viewModel => viewModel.IsLiked)

<script src="~/js/like.js"></script>

Catumblr/Views/Shared/_RenderPosts.cshtml
@model IEnumerable<Catumblr.DAL.Models.Post>
@foreach (var post in Model)
{
    <div class="jumbotron">
        <div class="container-fluid">
            <div class="col-md-10">
                <a asp-controller="Post" asp-action="GetPost" asp-route-id=@post.Id>
                    <h2>@post.Title</h2>
                </a>
            </div>
        </div>        
        <hr/>
        <h3>@post.Content</h3>
    </div>
}